name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@master
      - run: cargo build --release
      - run: zip -j brainseed-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}.zip target/release/brainseed
        if: runner.os != 'Windows'
      - run: Compress-Archive -Path .\target\release\brainseed.exe -DestinationPath .\brainseed-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}.zip
        if: runner.os == 'Windows'
      - name: Archive zip file
        uses: actions/upload-artifact@v3
        with:
          name: brainseed-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}.zip
          path: '*.zip'


  upload:
    name: release ${{ matrix.os }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload the zips files
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.zip'